# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         HTML-RelExtor
version:      0.01
version_from: lib/HTML/RelExtor.pm
installdirs:  site
requires:
    HTML::Parser:                  3
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
